apiVersion: v1
kind: Service
metadata:
  name: "{app_name}-service"
  namespace: "{namespace}"
spec:
  selector:
    app: "{app_name}-service"
  type: ClusterIP
  ports:
  - name: "{app_name}-service"
    protocol: TCP
    port: {port}
    targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{app_name}-index"
  namespace: "{namespace}"
data:
  index.html: |
    {index_html}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "{app_name}"
  namespace: "{namespace}"
  labels:
    app:  "{app_name}"
spec:
  selector:
    matchLabels:
      app: "{app_name}"
  replicas: {deployment_replicas}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  "{app_name}"
    spec:
      containers:
      - name:  "{app_name}"
        image:  nginx:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
          name:  "{app_name}"
        volumeMounts:
        - name: nginx-index-file
          mountPath: /usr/share/nginx/html/
      restartPolicy: Always
      volumes:
      - name: nginx-index-file
        configMap:
          name: "{app_name}-index"