apiVersion: apps/v1
kind: Deployment
metadata:
  name:  TPPythonOperator
  namespace: default
  labels:
    app:  TPPythonOperator
spec:
  selector:
    matchLabels:
      app: TPPythonOperator
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  TPPythonOperator
    spec:
      containers:
      - name:  TPPythonOperator
        image:  MYAPP:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always